version: "3.1"

services:
  mongo:
    image: mongo:4.2.3
    restart: always
    ports:
      - 27018:27017
    command: mongod --bind_ip_all
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
