apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-persistence-volume-claim-mongo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefilestorage
