kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefilestorage
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: trialstorageaccountut
reclaimPolicy: Retain
allowVolumeExpansion: true
